### ISSUE TITLE
Enable sign of commits

### ISSUE THREAD

**Issue by carusogabriel** [sgolemon/php-release#10]
Hey @sgolemon 👋🏻 

I've noticed that all the `git commit` commands do not sign themselves (https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Would you accept a patch adding this functionality?

I think we can use `git config --list | grep "commit.gpgsign=true` or `git config --list | grep "user.signingkey="` to check if the user either signs its commits or not :)

**Comment by sgolemon** [comment]
If the output of the release builder it includes a command invocation to run: `../bin/sign.sh some args ...`

I built it that way to avoid having to have access to any key material from inside the container.

That said, if you wanna make it a configurable option, I'm not against it.

**Comment by carusogabriel** [comment]
> If the output of the release builder it includes a command invocation to run: ../bin/sign.sh some args ...

Another option. I'll search how to amend commits and sign them, shouldn't be that difficult! I'll come up with a PR for either one of the cases

> I built it that way to avoid having to have access to any key material from inside the container.

Makes sense, the less we depend on the external, the better :)
